import './globals.css'
import SideBar from '../components/SideBar';
import { SessionProvider } from '../components/SessionProvider';
import { getServerSession } from 'next-auth';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import Login from '../components/Login'
import ClientProvider from '@/components/ClientProvider';
// import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ChatGPT Clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            // if we  donot have a session started
            <Login />
          ):(
            // if session already present 
            <div className="flex">
            <div className="bg-[#202123] max-w-xs h-screen overflow-auto md:min-w-[20rem]">
            <SideBar/>
            </div>
            
            {/* {client provider - thinking notification} */}

            {/* as we need a client side component at the top level for showing notification */}
            <ClientProvider />

            <div className="bg-[#343541] flex-1"> {children} </div>
            </div>

          )}
     
        </SessionProvider>
      
        
        
        </body>
    </html>
  )
}
